### ISSUE TITLE
안녕하세요. 잘 보았습니다.

### ISSUE THREAD

**Issue by KKodi-Sera** [kw-lee/2019compling1#1]
다름이 아니오라 example 로 문장을 하나씩 적어보는것 외에

엑셀 파일에 있는 column 하나를 1과 0으로 분류하게끔 할 수는 없나요?

혹시 할 수 있다면 코드를 어떻게 작성해야하나요?? ㅠㅠ

**Comment by kw-lee** [comment]
안녕하세요, 말씀해주신 내용은 엑셀 파일을 pandas를 이용해 dataframe 형태로 파이썬에 불러오고, tokenizing한 뒤 모형에 넣는 형태로 처리할 수 있을 것 같습니다.
